runtime config/**/*.vim

let mapleader=" "
set nocompatible
set number
set autowrite
set tabstop=4
set backspace=indent,eol,start
set mouse=a
syntax on
set hlsearch
filetype plugin indent on
set autoindent
set laststatus=2
set noshowmode

call pathogen#infect()
call pathogen#helptags()

" Easy-Motion

let g:EasyMotion_do_mapping = 0 " Disable default mappings

" Bi-directional find motion
" Jump to anywhere you want with minimal keystrokes, with just one key
" binding.
" `s{char}{label}`
" nmap s <Plug>(easymotion-s)
" or
" `s{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
nmap s <plug>(easymotion-s2)

" Turn on case insensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)



" Split configuration

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Copy/Paste - X11

vmap <C-C> "+y
nmap <C-V> "+p

" Lightline

let g:lightline = {'colorscheme' : 'seoul256'}

" Autocompletion

imap <Tab> <C-P>

" JavaComplete

autocmd Filetype java setlocal omnifunc=javacomplete#Complete
autocmd Filetype java setlocal completefunc=javacomplete#CompleteParamsInfo
inoremap <buffer> <C-X><C-U> <C-X><C-U><C-P>
inoremap <buffer> <C-S-Space> <C-X><C-U><C-P>

" DelimitTab

imap <C-K> <Plug>delimitMateS-Tab

" Syntastic

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


" Theme

syntax enable
set background=dark
set t_Co=256
colorscheme desert
hi LineNr ctermbg=236

					
" Indent Guides

let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=235
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=236
autocmd VimEnter * :IndentGuidesEnable



